import { SignIn, SignInButton, SignOutButton } from "@clerk/clerk-react";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home(props) {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { data } = api.posts.getAll.useQuery();


  return (
    <>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

        <SignInButton />

        <div>
          {data?.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div>
      </main>
    </>
  );
}
